object Dependencies {
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.versionKotlinStdlib}"
    const val core = "androidx.core:core-ktx:${Versions.versionCore}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.versionAppCompat}"
    const val materialDesign =
        "com.google.android.material:material:${Versions.versionMaterialDesign}"
    const val junit = "junit:junit:${Versions.versionJUnit}"
    const val junitExt = "androidx.test.ext:junit:${Versions.versionJUnitExt}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.versionEspresso}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.versionRetrofit}"
    const val convertorGson = "com.squareup.retrofit2:converter-gson:${Versions.versionRetrofit}"
    const val okHtttp = "com.squareup.okhttp3:okhttp:${Versions.versionOkHttp}"
    const val retrofitCoroutineCallAdapter =
        "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:${Versions.versionCallAdapter}"
    const val room = "androidx.room:room-runtime:${Versions.versionRoom}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.versionRoom}"
    const val roomCoroutineExt = "androidx.room:room-ktx:${Versions.versionRoom}"
    const val coroutines =
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.versionCoroutines}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.versionHilt}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.versionHilt}"
    const val fragmentKtx = "androidx.fragment:fragment-ktx:${Versions.versionFragmentKtx}"
    const val navigation = "androidx.navigation:navigation-ui-ktx:${Versions.versionNavigation}"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.versionNavigationFragment}"
    const val paging ="androidx.paging:paging-runtime:${Versions.versionPaging}"
    const val timber = "com.jakewharton.timber:timber:${Versions.versionTimber}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.versionGlide}}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.versionGlide}"
    const val coil = "io.coil-kt:coil:${Versions.versionCoil}"
}