object Versions {
    const val versionKotlin = "1.4.32"
    const val versionGradle = "4.1.3"
    const val versionKotlinStdlib = "1.3.2"
    const val versionCore = "1.3.2"
    const val versionAppCompat = "1.2.0"
    const val versionMaterialDesign = "1.3.0"
    const val versionJUnit = "4.+"
    const val versionJUnitExt = "1.1.2"
    const val versionEspresso = "3.3.0"
    const val versionRetrofit = "2.9.0"
    const val versionOkHttp = "4.9.0"
    const val versionHilt = "2.35"
    const val versionCallAdapter = "0.9.2"
    const val versionRoom = "2.3.0"
    const val versionCoroutines = "1.3.9"
    const val versionFragmentKtx = "1.4.0-alpha03"
    const val versionNavigation = "2.4.0-alpha03"
    const val versionNavigationFragment = "2.4.0-alpha03"
}